version: '3'

services:
  api:
    container_name: wishbox-api
    image: node:latest
    build:
      context: ./api
      dockerfile: Dockerfile
    env_file: api/.env
    volumes: 
      - ./api:/var/www
      - /var/www/node_modules
    ports:
      - "8080:3000"
    depends_on:
      - db
    networks:
      - wishbox_network
    command: npm run dev 

  db:
    container_name: mongo
    image: mongo:4.0.12
    ports:
      - "27019:27017"
    networks:
      - wishbox_network
networks:
  wishbox_network:
    driver: bridge